# Go Patriots!!!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

code {
    border: 1px solid {{ page.border }};
    background-color: {{ page.backA }};
}

pre {
    border: 1px solid {{ page.border }};
    background-color: {{ page.backA }};
    padding: 3px;
    margin-left: 1em;
}

pre code {
    border: none;
    background-color: {{ page.backA }};
}

blockquote {
    border: 1px dashed {{ page.border }};
    background-color: {{ page.backC }};
    padding: 0 0 0 0.5em;
}

# Site settings
title: Go Pats!!!
email: gopats@pats.com
description: > # this means to ignore newlines until "baseurl:"
  This site supports the New England Patriots and everything they do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gopatsrb
github_username:  gopats

# Build settings
markdown: kramdown
